+incdir+../../src/globals/
+incdir+../../src/hvl_top/rc/
+incdir+../../src/hvl_top/test/sequences/rc_sequences/
+incdir+../../src/hdl_top/rc_agent_bfm/
+incdir+../../src/hvl_top/ep/
+incdir+../../src/hvl_top/test/sequences/ep_sequences/
+incdir+../../src/hdl_top/ep_agent_bfm/
+incdir+../../src/hvl_top/env/
+incdir+../../src/hvl_top/env/virtual_sequencer/
+incdir+../../src/hvl_top/test/virtual_sequences/
+incdir+../../src/hvl_top/test/
+incdir+../../src/hdl_top/pcie_phy_interface/

../../src/globals/pcie_phy_globals_pkg.sv
../../src/hvl_top/rc/pcie_phy_rc_pkg.sv
../../src/hvl_top/ep/pcie_phy_ep_pkg.sv
../../src/hvl_top/test/sequences/rc_sequences/pcie_phy_rc_seq_pkg.sv
../../src/hvl_top/test/sequences/ep_sequences/pcie_phy_ep_seq_pkg.sv
../../src/hvl_top/env/pcie_phy_env_pkg.sv
../../src/hvl_top/test/virtual_sequences/pcie_phy_virtual_seq_pkg.sv
../../src/hvl_top/test/pcie_phy_test_pkg.sv
../../src/hdl_top/pcie_phy_interface/pcie_phy_if.sv
../../src/hdl_top/rc_agent_bfm/pcie_phy_rc_driver_bfm.sv
../../src/hdl_top/rc_agent_bfm/pcie_phy_rc_monitor_bfm.sv
../../src/hdl_top/rc_agent_bfm/pcie_phy_rc_agent_bfm.sv
../../src/hdl_top/ep_agent_bfm/pcie_phy_ep_driver_bfm.sv
../../src/hdl_top/ep_agent_bfm/pcie_phy_ep_monitor_bfm.sv
../../src/hdl_top/ep_agent_bfm/pcie_phy_ep_agent_bfm.sv
../../src/hdl_top/hdl_top.sv
../../src/hvl_top/hvl_top.sv
../../src/hdl_top/rc_assertions.sv
../../src/hdl_top/tb_rc_assertions.sv
../../src/hdl_top/ep_assertions.sv
../../src/hdl_top/tb_ep_assertions.sv
